services:
  - type: web
    name: chef-gpt-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: CORS_ORIGINS
        sync: false 